import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/navbar";

const myFont = localFont({
  src: [
    {
      path: "../font/SaoChingcha-Regular.otf",
      style: "normal",
      weight: "400",
    },
    {
      path: "../font/SaoChingcha-Bold.otf",
      style: "bold",
      weight: "00",
    },
    {
      path: "../font/SaoChingcha-Light.otf",
      style: "light",
      weight: "300",
    },
  ],
});

export const metadata: Metadata = {
  title: "Muang Thai Restaurant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.className} bg-[#242424] flex flex-col justify-center`}>
        <div className="bg-[url('/cover.svg')] bg-[length:1887px_1147px] bg-center h-screen bg-no-repeat w-full space-y-7">
          <Navbar />
          <div> {children}</div>
        </div>
      </body>
    </html>
  );
}
